### ISSUE TITLE
댓글의 삭제/수정 버튼 아이콘의 크기

### ISSUE THREAD

**Issue by mcnorton** [mcnorton/indischool40#17]
댓글의 삭제/수정 버튼 아이콘의 크기가 너무 큽니다.

<img width="286" alt="2018-01-02 15 44 15" src="https://user-images.githubusercontent.com/4551495/34476398-d372409a-efd3-11e7-8c05-a5adf383074c.png">

텍스트와 균형있는 크기로 조정이 필요합니다.

**Comment by mcnorton** [comment]
디자인 수정 작업 중이라 연락 받음.

**Comment by plextor97** [comment]
이건 디자인 작업중에 있습니다. 2018-01-02 수정중
